baseURL: "https://mbeyerstjerne.github.io/"
title: "Mark Beyer Stjerne"
theme: "PaperMod"

enableRobotsTXT: true

params:
  author: "Mark Beyer Stjerne"
  defaultTheme: dark
  disableThemeToggle: false

  assets:
    disableScrollBarStyle: false

  label:
    text: "Home"
    # icon: favicon.ico
    iconHeight: 0

  socialIcons:
    - name: Email
      url: "mailto:mbeyerstjerne@gmail.com"
    - name: GitHub
      url: "https://github.com/mbeyerstjerne"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/mbeyerstjerne/"

menu:
  main:
    - name: Work
      url: /projects/
      weight: 10

    - name: CV
      url: /cv/
      weight: 20

    - name: GitHub
      url: "https://github.com/mbeyerstjerne"
      weight: 30

markup:
  goldmark:
    renderer:
      unsafe: true